Feature/validator link to censor
GuiaBolso/hyperloop pull request #10
Opened 2018-07-31 15:19 UTC by thiagobardella

New validation format for detecting the path of encrypted fields

2018-07-31 18:21 UTC, jairogb requested changes

2018-07-31 18:21 UTC, jairogb commented on validator/src/main/kotlin/br/com/guiabolso/hyperloop/validation/EventValidator.kt
> +        if (schemaPayloadSpec == null)
Validar empty fields

2018-07-31 18:21 UTC, jairogb commented on validator/src/main/kotlin/br/com/guiabolso/hyperloop/validation/EventValidator.kt
> +            if (userId == null)
Adicionar validação de JsonNull

2018-07-31 18:21 UTC, jairogb commented on validator/src/main/kotlin/br/com/guiabolso/hyperloop/validation/EventValidator.kt
> +            if (origin == null)
Adicionar validação de JsonNull

2018-08-01 17:31 UTC, bruno-ortizgb approved these changes

2018-08-01 17:32 UTC, merged