Feature/adding map type
GuiaBolso/hyperloop pull request #17
Opened 2018-11-14 17:06 UTC by jairogb

Adding map structure to Hyperloop

2018-11-14 18:52 UTC, thiagobardella approved these changes

2018-11-20 16:04 UTC, bruno-ortiz requested changes

2018-11-20 16:04 UTC, bruno-ortiz commented on validator/src/main/kotlin/br/com/guiabolso/hyperloop/validation/types/SchemaNodeTypeParser.kt
> +                if (attrs[0] != "string") throw WrongSchemaFormatException("Illegal type $type. Map key must be string")
Se tem que ser sempre string, não é melhor deixar essa informação implicita?

2018-11-20 16:04 UTC, bruno-ortiz commented on build.gradle
> -        publish_version = '1.3.5'
1.4.0 tem feature nova

2018-11-20 17:38 UTC, bruno-ortiz approved these changes

2018-11-20 17:38 UTC, merged