Adiciona integração com s3 para carregar schemas
GuiaBolso/hyperloop pull request #3
Opened 2018-07-12 19:13 UTC by andrade-ramon

2018-07-13 14:10 UTC, bruno-ortiz requested changes

2018-07-13 14:10 UTC, bruno-ortiz commented on validator/src/main/kotlin/br/com/guiabolso/schemas/SchemaRepository.kt
> +    fun get(schema : String) : String
Eu criaria uma abstração para esse parametro schema. Talvez um data class que ja tenha o nome e versão do schema

2018-07-13 14:10 UTC, bruno-ortiz commented on validator/build.gradle
> +    compile 'com.amazonaws:aws-java-sdk-s3:1.11.273'
atualizar pra ultima versão da sdk.. acredito que é 1.11.366

2018-07-13 14:10 UTC, bruno-ortiz commented on validator/src/main/kotlin/br/com/guiabolso/schemas/SchemaRepositoryFactory.kt
> +    val schemaRepository: SchemaRepository = when (storageType()) {
Acho que como é uma LIB não é necessário ter essa factory..

Sugestão: Deixaria o SchemaRepository como parametro do Validator e quem for usar instancia da maneira que preferir

2018-07-17 20:36 UTC, thiagobardella approved these changes

2018-07-17 20:37 UTC, bruno-ortiz approved these changes

2018-07-17 20:48 UTC, merged